services:
  postgres:
    image: postgres:15
    container_name: parking_postgres
    environment:
      POSTGRES_DB: parking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  backend:
    build: .
    container_name: parking_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data: